[build]
  publish = "public/"
  command = "npm run build"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images",
    ".cache"
  ]

[[redirects]]
  from = "/collection/wholesale/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/collection/wholesale/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true

[functions]
  directory = "functions"